server:
  port: 8093
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/route?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: EeLcDmS2022*
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
  